apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lmsrepset
  labels:
    app: lmsrs
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: lmsweb
      labels:
        app: lmsweb
        tier: front-end
    spec:
      containers:
      - name: lmsweb
        image: kunohdere/lms-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80 