apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lms-db-statefulset
  namespace: lms-beta
  labels:
    app: lms-db-postgres
    env: test
    tier: dbend
spec:
  selector:
    matchLabels:
      app: lms-db-psql
      env: test
  serviceName: lms-db-service
  replicas: 2
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: lms-db-psql
        env: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: lms-db-psql-container
        image: postgres:17-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: lms-db-port
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: lms-dbconfig
        - secretRef:
            name: psql-secret-data
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1"
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB && psql -U ${POSTGRES_USER} -d ${POSTGRE_DB} -c 'SELECT 1;'"
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5

  volumeClaimTemplates:
  - metadata:
      name: postgresdata
      namespace: lms-beta
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
