apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-db-pv
  namespace: lms-beta
  labels:
    type: local
    app: lms-postgres-persitent-volume
spec:
  storageClassName: manual
  capacity:
    storage: "5Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
