apiVersion: v1
kind: Service
metadata:
  name: lms-db-service
  namaspace: lms
  labels:
    app: lms-postgres-service
spec:
  type: ClusterIP
  selector:
    app: lms-db
  ports:
    - port: 9911
      targetPort: 5432
