apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-db-persistent-volume
  namaspace: lms
  labels:
    type: local
    app: postgres-persitent-volume
spec:
  storageClassName: manual
  capacity:
    storage: "5Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
