apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lms-db-statefulset
  namespace: lms-beta
  labels:
    app: lms-db-postgres
    env: test
spec:
  selector:
    matchLabels:
      app: db-psql
  serviceName: lms-db-service
  replicas: 2
  template:
    metadata:
      labels:
        app: db-psql
    spec:
      containers:
      - name: db-psql
        image: postgres:17-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgres
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: lms-dbconfig
        - secretRef:
            name: psql-secret-data
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresdata
      namespace: lms-beta
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
