apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-db-claim
  namespace: lms-beta
  labels:
    app: postgres-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"
  volumeMode: Filesystem
