apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-db-claim
  namaspace: lms
  labels:
    app: postgres-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
  volumeMode: Filesystem
