apiVersion: v1
kind: Service
metadata:
  name: lms-db-service
  namespace: lms-beta
  labels:
    app: lms-db-service
    env: test
spec:
  type: ClusterIP
  # clusterIP: None
  selector:
    app: lms-db-psql
    env: test
  ports:
    - protocol: TCP
      port: 9911
      targetPort: 5432
