apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lms-beta
  name: pod-reader
  env: test
rules:
- apiGroups: [""] # core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
