apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lms-role-binding
  namespace: lms-beta
  env: test
subjects:
- kind: User
  name: kunnoh # case sensiive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
