apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lms-beta
  name: admin
  env: test
rules:
- apiGroups: 
  - ""
  resources: 
    - pods
  verbs: 
    - get
    - watch
    - list
