apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-rolebinding
  namespace: lms-beta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewer-role
subjects:
  - kind: ServiceAccount
    name: viewer-role
    namespace: lms-beta