apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-api-deploy
  namaspace: lms
  labels:
    app: lms-api-deployment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-api-app
      tier: backend
  template:
    metadata:
      labels:
        app: lms-api-app
        tier: backend
    spec:
      containers:
        - name: lms-api-container
          image: kunohdere/lms-api:latest

          ports:
            - containerPort: 5521

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "196Mi"
              cpu: "300m"

          envFrom:
            - configMapRef:
                name: lms-api-config

          livenessProbe:
            httpGet:
              path: /health
              port: 5521
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 5521
            initialDelaySeconds: 5
            periodSeconds: 5
