apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-api-config
  namespace: lms-beta
  labels:
    name: lms-api-config
    tier: env
data:
  DB_HOST: lms-db-service
  DB_PORT: "9911"
  DB_NAME: test
  PORT: "5521"
  TOKEN_EXPIRY: 10m
  REFRESH_TOKEN_EXPIRY: 4h
  TOKEN_MAXAGE: 1h
