apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-api-deploy
  namespace: lms-beta
  labels:
    app: lms-api-deployment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-api-app
      tier: backend
  template:
    metadata:
      labels:
        app: lms-api-app
        tier: backend
    spec:
      containers:
        - name: lms-api-container
          image: kunohdere/lms-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5521
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: lms-api-config
            - secretRef:
                name: lms-api-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 5521
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5521
            initialDelaySeconds: 35
            periodSeconds: 5
