apiVersion: v1
kind: Service
metadata:
  name: lms-api-service
  namespace: lms-beta
  labels:
    app: lms-api-app-service
spec:
  type: NodePort
  selector:
    app: lms-api-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 5521
      nodePort: 30090
