apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-api-config
  namaspace: lms
  labels:
    name: lms-api-config
    tier: env
data:
  DB_HOST: lms-db-service
  DB_PORT: "9911"
  DB_NAME: test
  PORT: "5521"
  TOKEN_EXPIRY: 10m
  REFRESH_TOKEN_EXPIRY: 24h
  TOKEN_MAXAGE: 12h
