apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-web-deploy
  namespace: lms-beta
  labels:
    app: lms-web-deployment
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-web
  template:
    metadata:
      labels:
        app: lms-web
        tier: frontend
    spec:
      containers:
      - name: lms-web
        image: kunohdere/lms-web:1.0.0
        ports:
        - containerPort: 80