apiVersion: v1
kind: Service
metadata:
  name: lms-web-service
  namespace: lms-beta
  labels:
    app: lms-web-app-service
spec:
  type: NodePort
  selector:
    app: lms-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
