apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-web-deploy
  namespace: lms-beta
  labels:
    app: lms-web-deployment
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-web
  template:
    metadata:
      labels:
        app: lms-web
        tier: frontend
    spec:
      containers:
      - name: lms-web
        image: kunohdere/lms-web:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20